<a href="https://colab.research.google.com/github/Aravin423/ad_classes/blob/main/linearregression_with_travel_destination.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LinearRegression
from xgboost import XGBClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import accuracy_score, mean_squared_error
import seaborn as sns
from sklearn.preprocessing import StandardScaler, OneHotEncoder, LabelEncoder
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression

In [ ]:
df = pd.read_excel("/content/travel_destination_recommendation_dataset.xlsx", engine='openpyxl')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 15 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   user_id                  100000 non-null  int64
 1   destination_id           100000 non-null  int64
 2   destination_name         100000 non-null  object
 3   country                  100000 non-null  object
 4   user_age                 100000 non-null  float64
 5   trip_duration_days       100000 non-null  int64
 6   travel_budget_usd        100000 non-null  float64
 7   popularity_score         100000 non-null  float64
 8   travel_category          100000 non-null  object
 9   climate_preference       100000 non-null  object
 10  flight_duration_hours    100000 non-null  float64
 11  rating                   100000 non-null  float64
 12  accommodation_type       100000 non-null  object
 13  previous_visits          100000 non-null  int64
 14  special_deals_available  100000 non-null  object
dtypes: float64(5), int64(4), object(6)
memory usage: 11.4+ MB

In [ ]:
df.head()

,user_id,destination_id,destination_name,country,user_age,trip_duration_days,travel_budget_usd,popularity_score,travel_category,climate_preference,flight_duration_hours,rating,accommodation_type,previous_visits,special_deals_available
0,15796,9366,Paris,France,44.4,8,2833.71,0.288,Adventure,Warm,7.8,3.9,Hostel,4,Yes
1,861,1928,London,UK,45.0,14,3634.42,0.727,Cultural,Moderate,17.1,4.3,Hostel,4,Yes
2,38159,9541,Amsterdam,Netherlands,27.4,5,4714.07,0.537,Backpacking,Moderate,7.9,5.0,Hostel,1,No
3,44733,3708,Los Angeles,USA,38.4,14,4968.14,0.757,Honeymoon,Cold,16.4,4.4,Camping,0,No
4,11285,3361,Rio de Janeiro,Brazil,53.6,5,542.09,0.517,Backpacking,Moderate,2.7,5.0,Airbnb,4,No

In [ ]:
print("Dataset Info:")
print(df.info())
print("\nSummary Statistics:")
print(df.describe())
print("\nColumns in dataset:", df.columns)

Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 15 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   user_id                  100000 non-null  int64
 1   destination_id           100000 non-null  int64
 2   destination_name         100000 non-null  object
 3   country                  100000 non-null  object
 4   user_age                 100000 non-null  float64
 5   trip_duration_days       100000 non-null  int64
 6   travel_budget_usd        100000 non-null  float64
 7   popularity_score         100000 non-null  float64
 8   travel_category          100000 non-null  object
 9   climate_preference       100000 non-null  object
 10  flight_duration_hours    100000 non-null  float64
 11  rating                   100000 non-null  float64
 12  accommodation_type       100000 non-null  object
 13  previous_visits          100000 non-null  int64
 14  special_deals_available  100000 non-null  object
dtypes: float64(5), int64(4), object(6)
memory usage: 11.4+ MB
None

Summary Statistics:
             user_id  destination_id       user_age  trip_duration_days  \
count  100000.000000   100000.000000  100000.000000       100000.000000
mean    24935.663570     5006.863560      35.377249           11.486190
std     14406.960108     2882.085456      11.167062            5.192444
min         1.000000        1.000000      18.000000            3.000000
25%     12487.750000     2523.000000      26.900000            7.000000
50%     24793.500000     5012.000000      34.900000           11.000000
75%     37382.250000     7502.000000      43.000000           16.000000
max     49999.000000     9999.000000      70.000000           20.000000

       travel_budget_usd  popularity_score  flight_duration_hours  \
count      100000.000000     100000.000000          100000.000000
mean         5264.996549          0.692745              11.016241
std          2736.276841          0.188538               5.192600
min           500.000000          0.000000               2.000000
25%          2894.022500          0.563000               6.500000
50%          5279.960000          0.698000              11.000000
75%          7632.207500          0.834000              15.500000
max          9999.980000          1.000000              20.000000

              rating  previous_visits
count  100000.000000    100000.000000
mean        4.238301         1.993610
std         0.607699         1.412597
min         1.100000         0.000000
25%         3.800000         1.000000
50%         4.300000         2.000000
75%         4.800000         3.000000
max         5.000000         4.000000

Columns in dataset: Index(['user_id', 'destination_id', 'destination_name', 'country', 'user_age',
       'trip_duration_days', 'travel_budget_usd', 'popularity_score',
       'travel_category', 'climate_preference', 'flight_duration_hours',
       'rating', 'accommodation_type', 'previous_visits',
       'special_deals_available'],
      dtype='object')

In [ ]:
features = ["trip_duration_days", "travel_budget_usd", "popularity_score",
            "climate_preference", "flight_duration_hours"]
target = "rating"

In [ ]:
features_df = df[features]
target_df = df[target]

In [ ]:
features_df

,trip_duration_days,travel_budget_usd,popularity_score,climate_preference,flight_duration_hours
0,8,2833.71,0.288,Warm,7.8
1,14,3634.42,0.727,Moderate,17.1
2,5,4714.07,0.537,Moderate,7.9
3,14,4968.14,0.757,Cold,16.4
4,5,542.09,0.517,Moderate,2.7
...,...,...,...,...,...
99995,9,6124.10,0.551,Cold,7.5
99996,17,9974.27,0.856,Warm,18.7
99997,3,4282.73,0.546,Warm,13.2
99998,3,7207.08,0.925,Cold,16.7
99999,7,9789.01,0.697,Warm,6.8

In [ ]:
target_df

0        3.9
1        4.3
2        5.0
3        4.4
4        5.0
        ...
99995    3.6
99996    4.1
99997    4.9
99998    4.8
99999    4.8
Name: rating, Length: 100000, dtype: float64